package me.stivendarsi.tigerBeach.itemmanager.editor.editMenus;

public enum ItemEditorType {
   PAINTING_VARIANT,
   BLOCKS_ATTACKS,
   POTION_CONTENTS,
   POTION_DURATION_SCALE,
   PROFILE,
   RARITY,
   REPAIRABLE,
   REPAIR_COST,
   DAMAGE,
   MAX_STACK_SIZE,
   STORED_ENCHANTMENTS,
   TOOL,
   TOOLTIP_DISPLAY,
   TOOLTIP_STYLE,
   BREAK_SOUND,
   EQUIPPABLE,
   FOOD,
   ITEM_MODEL,
   LORE,
   DYED_COLOR,
   DEATH_PROTECTION,
   CONSUMABLE,
   ENCHANTMENT_GLINT_OVERRIDE,
   ENCHANTMENTS,
   ITEM_NAME,
   CUSTOM_NAME;

   // $FF: synthetic method
   private static ItemEditorType[] $values() {
      return new ItemEditorType[]{PAINTING_VARIANT, BLOCKS_ATTACKS, POTION_CONTENTS, POTION_DURATION_SCALE, PROFILE, RARITY, REPAIRABLE, REPAIR_COST, DAMAGE, MAX_STACK_SIZE, STORED_ENCHANTMENTS, TOOL, TOOLTIP_DISPLAY, TOOLTIP_STYLE, BREAK_SOUND, EQUIPPABLE, FOOD, ITEM_MODEL, LORE, DYED_COLOR, DEATH_PROTECTION, CONSUMABLE, ENCHANTMENT_GLINT_OVERRIDE, ENCHANTMENTS, ITEM_NAME, CUSTOM_NAME};
   }
}
